#!/usr/bin/env bash
# This bash script is displaying the time for 12 hrs and 59 mins

hrs=0

while [ $hrs -le 12 ]
do
	echo "Hour: $hrs"
	min=1
	while [ $min -le 59 ]
	do
		echo "$min"
		((min++))
	done	
	((hrs++))
done
